### ISSUE TITLE
Fix solc usage

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-network-consensus-contracts#137]
`poa-bytecode` script `require('solc')`, but solc dependency is missing in the `package.json`.

Also, MoC instruction emphasizes on step 2 that binary solc is required (not the one from npm) https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup#poa-network-consensus-contract 
but it's probably outdated and doesn't seem to work anyway (solc from npm is still required to run the script).

It needs to be clarified if solc binary should be installed separately and how to use it + if npm module is also required, package.json should be updated.

**Comment by varasev** [comment]
> `poa-bytecode` script `require('solc')`, but solc dependency is missing in the `package.json`.

Yes, I added `solc` into `scripts/package.json` in https://github.com/poanetwork/poa-network-consensus-contracts/pull/139 - it's waiting for approval.

> It needs to be clarified if solc binary should be installed separately and how to use it

@rstormsf @vbaranov please, take a look at step 2 on [this page](https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup#poa-network-consensus-contract) - is it still required to use `solc` not from `npm` for some reason?

**Comment by vbaranov** [comment]
@varasev we were using a binary package of `solc` because it was a requirement of using [Python Solidity flattener](https://github.com/BlockCatIO/solidity-flattener#requirements). I think we shouldn't depend on it anymore. Instead, we could use [truffle-flattener](https://www.npmjs.com/package/truffle-flattener) or [POA Solidity flattener](https://github.com/poanetwork/solidity-flattener) 😄, the first one is more preferable because it has an npm package. I guess we could change flattener in frames of #139 PR and also change `README` sections:
1. [Prerequisites section](https://github.com/poanetwork/poa-network-consensus-contracts#prerequisites)
2. [Start POA Network section](https://github.com/poanetwork/poa-network-consensus-contracts#start-poa-network)

After that we could change a [wiki guide](https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup#poa-network-consensus-contract)

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-network-consensus-contracts/pull/139.
