### ISSUE TITLE
Hardcoded MoC in PoaNetworkConsensus contract

### ISSUE THREAD

**Issue by jordipainan** [poanetwork/poa-network-consensus-contracts#61]
Hi! Im playing with your PoaNetworkConsensus contract and I don't understand one step.
Also Parity gets stuck in the process. If I change the constructor from:
```
function PoaNetworkConsensus(address _masterOfCeremony, address[] validators) public {
        // TODO: When you deploy this contract, make sure you hardcode items below
        // Make sure you have those addresses defined in spec.json
        require(_masterOfCeremony != address(0));
        masterOfCeremony = _masterOfCeremony;
        currentValidators = [masterOfCeremony];
        .... 
}
```
To:

```
function PoaNetworkConsensus(address[] validators) public {
        // TODO: When you deploy this contract, make sure you hardcode items below
        // Make sure you have those addresses defined in spec.json
        masterOfCeremony = 0x....;
        require(masterOfCeremony != address(0));
        currentValidators = [masterOfCeremony];
        .... 
}
```

It compiles well and I'm able to put the bytecode in the spec.json as a precompiled contract.
Then I start the network with: `parity --config basictoml.toml`
When I execute this command parity is loading the .toml file forever with 99% of CPU usage.
The rest of the contract is the same.

I don't know what happens because every time I set up a PoA, if the precompiled contract works bad, parity throws an exception. Possibly I made a mistake with the code mentioned before but im not sure. 
Thank you in advance and forgive me if I did not understand well the solidity code.

**Comment by jordipainan** [comment]
Hi ! Sorry I mistyped it here, but not in my code. Im gonna edit now in the issue.

**Comment by vbaranov** [comment]
@jordipainan 

>It compiles well and I'm able to put the bytecode in the spec.json as a precompiled contract.`

how do you compile `PoaNetworkConsensus` and what bytecode you set in the `spec`? I am asking because `PoaNetworkConsensus` has input parameters in the constructor.

Also, 
- what is your `basictoml.toml` content?
- what is your `spec.json` content?
- which Parity version are you using?

Consider using https://github.com/poanetwork/poa-test-setup#start-moc-node script to start POA network. It uses https://github.com/poanetwork/poa-network-consensus-contracts repo as a submodule. You can change the source of submodule to your own forked repo with contracts to test, if your setup is correct.

**Comment by jordipainan** [comment]
Hi @vbaranov , my fault, your code works like a charm. I pasted the wrong bytecode in the spec (with not expected params in the constructor). 
I opened the issue because I got a lot of errors in the past trying to build my concept of PoA with the constructor and I thought its possibly the same (an error in the contract and not in the client) but not the case.  
On the other hand Parity still gets stuck, I reported it to the team ^^ .
Thank you and sorry for the inconvenience.
