### ISSUE TITLE
(Feature) finalize immediately with the last vote

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/poa-network-consensus-contracts#91]
Relates to https://github.com/poanetwork/RFC/issues/8

**Comment by vbaranov** [comment]
@varasev were you planning to include this feature request to refactored contracts?

**Comment by varasev** [comment]
@vbaranov I wasn't, because this is a separate task, but if it's necessary, I'll give this task higher priority and include it in the current set of tasks that should be implemented before hard-fork.

**Comment by varasev** [comment]
This was implemented and covered by tests in #113 

I didn't include a calling of finalization function inside `vote` method because there can be a blocking (in case of any errors) if `_finalizeBallot` reverts, so the last validator won't be able to vote in this case and will be confused.

Therefore I suggest this implementation that assumes any validator should call `finalize` method separately by the same principle that works now.

These changes cover https://github.com/poanetwork/RFC/issues/8.
